2020-06-30 23:07:45 [DEBUG] ConnectionManager:38 - Close connection
2020-06-30 23:11:23 [INFO ] ConnectionManager:24 - Creating connection to data base
2020-06-30 23:11:29 [DEBUG] ConnectionManager:33 - Connection was created successfully
2020-06-30 23:11:29 [DEBUG] UserServiceImpl:40 - Save new user User{id=null, firstName='Гладун', lastName='Олег', email='oleg@gladun.com', role='USER', password='oleg123', amountOfMoney=0.0, courseId=null}
2020-06-30 23:11:29 [ERROR] UserRepositoryImpl:102 - Error while saving userUser{id=null, firstName='Гладун', lastName='Олег', email='oleg@gladun.com', role='USER', password='oleg123', amountOfMoney=0.0, courseId=null}
java.sql.SQLSyntaxErrorException: Unknown column 'course_id' in 'field list'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
	at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:370)
	at repository.impl.UserRepositoryImpl.save(UserRepositoryImpl.java:100)
	at repository.impl.UserRepositoryImpl.save(UserRepositoryImpl.java:14)
	at service.impl.UserServiceImpl.save(UserServiceImpl.java:41)
	at service.impl.UserServiceImpl.save(UserServiceImpl.java:13)
	at Main.main(Main.java:22)
2020-06-30 23:11:29 [DEBUG] ConnectionManager:38 - Close connection
2020-06-30 23:13:57 [INFO ] ConnectionManager:24 - Creating connection to data base
2020-06-30 23:14:01 [DEBUG] ConnectionManager:33 - Connection was created successfully
2020-06-30 23:14:01 [DEBUG] UserServiceImpl:40 - Save new user User{id=null, firstName='Гладун', lastName='Олег', email='oleg@gladun.com', role='USER', password='oleg123', amountOfMoney=0.0, courseId=null}
2020-06-30 23:14:02 [ERROR] UserRepositoryImpl:102 - Error while saving userUser{id=null, firstName='Гладун', lastName='Олег', email='oleg@gladun.com', role='USER', password='oleg123', amountOfMoney=0.0, courseId=null}
java.sql.SQLSyntaxErrorException: Unknown column 'course_id' in 'field list'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
	at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:370)
	at repository.impl.UserRepositoryImpl.save(UserRepositoryImpl.java:100)
	at repository.impl.UserRepositoryImpl.save(UserRepositoryImpl.java:14)
	at service.impl.UserServiceImpl.save(UserServiceImpl.java:41)
	at service.impl.UserServiceImpl.save(UserServiceImpl.java:13)
	at Main.main(Main.java:22)
2020-06-30 23:14:02 [DEBUG] ConnectionManager:38 - Close connection
2020-06-30 23:18:17 [INFO ] ConnectionManager:24 - Creating connection to data base
2020-06-30 23:18:22 [DEBUG] ConnectionManager:33 - Connection was created successfully
2020-06-30 23:18:22 [DEBUG] UserServiceImpl:40 - Save new user User{id=null, firstName='Гладун', lastName='Олег', email='oleg@gladun.com', role='USER', password='oleg123', amountOfMoney=0.0, courseId=null}
2020-06-30 23:18:22 [ERROR] UserRepositoryImpl:102 - Error while saving userUser{id=null, firstName='Гладун', lastName='Олег', email='oleg@gladun.com', role='USER', password='oleg123', amountOfMoney=0.0, courseId=null}
java.sql.SQLSyntaxErrorException: Unknown column 'course_id' in 'field list'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
	at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:370)
	at repository.impl.UserRepositoryImpl.save(UserRepositoryImpl.java:100)
	at repository.impl.UserRepositoryImpl.save(UserRepositoryImpl.java:14)
	at service.impl.UserServiceImpl.save(UserServiceImpl.java:41)
	at service.impl.UserServiceImpl.save(UserServiceImpl.java:13)
	at Main.main(Main.java:22)
2020-06-30 23:18:22 [DEBUG] ConnectionManager:38 - Close connection
2020-06-30 23:26:08 [INFO ] ConnectionManager:24 - Creating connection to data base
2020-06-30 23:26:12 [DEBUG] ConnectionManager:33 - Connection was created successfully
2020-06-30 23:26:12 [DEBUG] UserServiceImpl:40 - Save new user User{id=null, firstName='Гладун', lastName='Олег', email='oleg@gladun.com', role='USER', password='oleg123', amountOfMoney=0.0, courseId=null}
2020-06-30 23:26:12 [ERROR] UserRepositoryImpl:102 - Error while saving userUser{id=null, firstName='Гладун', lastName='Олег', email='oleg@gladun.com', role='USER', password='oleg123', amountOfMoney=0.0, courseId=null}
java.sql.SQLSyntaxErrorException: Unknown column 'course' in 'field list'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
	at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:370)
	at repository.impl.UserRepositoryImpl.save(UserRepositoryImpl.java:100)
	at repository.impl.UserRepositoryImpl.save(UserRepositoryImpl.java:14)
	at service.impl.UserServiceImpl.save(UserServiceImpl.java:41)
	at service.impl.UserServiceImpl.save(UserServiceImpl.java:13)
	at Main.main(Main.java:22)
